language: elixir

elixir:
  - 1.3.2
  - 1.4.0-rc.1

otp_release:
  - 18.2
  - 19.1

matrix:
  # We are only interested on the newest/oldest pair
  exclude:
    - elixir: 1.4.0-rc.1
      otp_release: 18.2
    - elixir: 1.3.2
      otp_release: 19.1

sudo: false

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
